name: Python CI

on: [push, pull_request]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ libgdal-dev python3-dev
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test critical imports
      run: |
        python -c "
        try:
            from main import app
            print('✓ FastAPI app import: SUCCESS')
        except Exception as e:
            print(f'✗ FastAPI app import: FAILED - {e}')
            exit(1)
        "
    
    - name: Install flake8 and run linting
      run: |
        pip install flake8
        flake8 app/ --max-line-length=127 --extend-ignore=E203,W503,E501 --count --show-source --statistics
