name: Python CI

on: [push, pull_request]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++ libgdal-dev python3-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            echo "✅ Found backend/requirements.txt"
            pip install -r requirements.txt
          elif [ -f ../requirements.txt ]; then
            echo "✅ Found root-level requirements.txt"
            pip install -r ../requirements.txt
          else
            echo "⚠️ No requirements.txt found. Skipping dependency installation."
          fi

      - name: Test critical imports
        run: |
          python - <<'EOF'
          try:
              from main import app
              print('✓ FastAPI app import: SUCCESS')
          except Exception as e:
              print(f'✗ FastAPI app import: FAILED - {e}')
              exit(1)
          EOF

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 app/ --max-line-length=127 --extend-ignore=E203,W503,E501 --count --show-source --statistics

      - name: Run tests with pytest
        run: |
          pip install pytest pytest-asyncio
          pytest --maxfail=1 --disable-warnings -q
